on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: release message
        run: |
          echo "${GITHUB_REF#refs/tags/}"
          git tag -n999
          git tag -n999 "${GITHUB_REF#refs/tags/}" > ${{ github.workflow }}-CHANGELOG.txt
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workflow }}-CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ryantm/test-github-actions
